export default function createToolbar(newFn, openFn, saveFn) {
	return [
		{
			name: "New",
			action: newFn,
			className: "fa fa-file-plus",
			title: "New",
			noDisable: true,
		},
		{
			name: "Open",
			action: openFn,
			className: "fa fa-folder-open",
			title: "Open",
			noDisable: true,
		},
		{
			name: "Save",
			action: saveFn,
			className: "fa fa-save title-text",
			title: "Save",
			noDisable: true,
		},
		"|",
		"bold",
		"italic",
		"strikethrough",
		"|",
		"heading-1",
		"heading-2",
		"heading-3",
		"|",
		"quote",
		"code",
		"|",
		"ordered-list",
		"unordered-list",
		"|",
		"link",
		"image",
		"table",
		"|",
		"preview",
		// "guide",
	];
}